//
// Created by Fleshmix on 02.11.2019.
//

#ifndef STACK_STACK_ERROR_H
#define STACK_STACK_ERROR_H

#define NULL_DATA_POINTER 101
#define ZERO_CAPACITY 102
#define BAD_REALLOC 103
#define NEGATIVE_SIZE 104
#define BAD_DATA_HASH 105
#define DEAD_DATA_CANARY 106
#define DEAD_STACK_CANARY 107
#define STACK_ZERO_POINTER 108
#define BAD_STACK_HASH 109

#endif //STACK_STACK_ERROR_H
